rules:
    disabled: []
    custom: []
git:
    maxFileSize: 10000000
code-quality:
    linters:
        - pylint
        - mypy
        - black
        - isort
        - bandit
testing:
    report: "/path/to/artifacts/tests-report.xml"
    targets:
        minimum: 1
        ratio:
            tests: 1
            other: 4
    coverage:
        report: "/path/to/artifacts/coverage.xml"
        targets:
            line: 80