name: Data Collection
on:
  push:
    branches:
      - '*'
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 5,17 * * *'
jobs:
  update_data:
    runs-on: ubuntu-latest
    container: ngavalas/remlabase:latest
    steps:
      - uses: actions/checkout@v3
      - run: dvc remote modify gdrive_remote gdrive_use_service_account true
      - run: dvc remote modify gdrive_remote gdrive_service_account_json_key_file key.json
      - name: let's see
        env:
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
        run: |
          dvc pull
      - run: ls
      - run: ls data
      - name: Automatic Data Collection
        run: |
          python src/data_collection.py