name: Data Collection
on:
  push:
    branches:
      - '*'
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 5,17 * * *'
jobs:
  update_data:
    runs-on: ubuntu-latest
    container: ngavalas/remlabase:latest
    steps:
      - uses: actions/checkout@v3
      - name: Collect Data and Update train dataset
        run: dvc pull - r origin
        env:
          GDRIVE_CREDENTIALS_DATA: $
      - run: ls
      - run: ls data
      - name: Automatic Data Collection
        run: |
          python src/data_collection.py