name: Data Collection
on:
  push:
    branches:
      - '*'
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 5,17 * * *'
jobs:
  update_data:
    runs-on: ubuntu-latest
    container: ngavalas/remlabase:latest
    steps:
      - uses: actions/checkout@v3
      - run: dvc remote modify gdrive_remote gdrive_use_service_account true
      - name: Pull Data
        env:
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
        run: |
          dvc pull
      - run: pip install stackapi
      - name: Automatic Data Collection
        run: |
          python src/data_collection.py
      - run: ls
      - run: ls .dvc/tmp
      - run: dvc remote modify gdrive_remote gdrive_service_account_user_email '919001351043-compute@developer.gserviceaccount.com'
      - name: Push Data
        env:
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
        run: |
          dvc push -v
      - run: cat .dvc/config
      - name: setup git config
        run: |
          # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Commit
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Stage the file, commit and push
          git add .
          git status
          git commit -m "Data Collection"
          git push origin main

      - run: cat data.dvc