name: ML Pipeline
on: [push]
jobs:
  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.8"
      - run: |
          pip install -r requirements.txt
      - name: mllint analysis
        run: |
          mllint
      - name: pylint analysis
        run: |
          find . -name '*.py' -exec pylint {} \;
  tests:
    runs-on: ubuntu-latest
    needs: static-analysis
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.8"
      - run: |
          pip install -r requirements.txt
      - name: Run tests
        run: |
          pytest --junitxml=tests-report.xml --cov=. --cov-report=xml