name: ML Pipeline
on: [push]
jobs:
  static-analysis:
    runs-on: ubuntu-latest
    container: ngavalas/remlabase:latest
    needs: tests
    steps:
      - uses: actions/checkout@v3
      - run: ls -l
      - name: mllint analysis
        run: |
          mllint
      - name: pylint analysis
        run: |
          find . -name '*.py' -exec pylint {} \;
  tests:
    runs-on: ubuntu-latest
    container: ngavalas/remlabase:latest
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: |
          pytest --junitxml=tests-report.xml --cov=. --cov-report=xml
      - run: ls -l