name: ML Pipeline
on: [push]
jobs:
  static-analysis:
    runs-on: ubuntu-latest
    container: ngavalas/remlabase:latest
    needs: tests
    steps:
      - uses: actions/checkout@v3
      - name: Download Docker Image (Artifact)
        uses: actions/download-artifact@v2
        with:
          name: docker-artifact
          path: path/to/artifacts
      - run: ls path/to/artifacts
      - uses: actions/checkout@v2
      - name: mllint analysis
        run: |
          mllint
      - name: pylint analysis
        run: |
          find . -name '*.py' -exec pylint {} \;
  tests:
    runs-on: ubuntu-latest
    container: ngavalas/remlabase:latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          mkdir -p path/to/artifacts
      - name: Run tests
        run: |
          pytest --junitxml=/path/to/artifacts/tests-report.xml --cov=/path/to/artifacts/ --cov-report=xml
      - run: ls -l
      - uses: actions/upload-artifact@v2
        with:
            name: docker-artifact
            path: path/to/artifacts